[package]
name = "cargo-get"
version = "0.3.2"
authors = ["Nicolai Unrein <n.unrein@gmail.com>"]
edition = "2018"
description = "Cargo plugin to easily query information from Cargo.toml files"
license = "Apache-2.0/MIT"
categories = ["command-line-utilities", "config", "development-tools", "development-tools::cargo-plugins", "parsing"]
keywords = ["binary", "cargo", "cli", "dev-tools", "query"]
readme = "README.md"
repository = "https://github.com/nicolaiunrein/cargo-get"
include = ["src/**/*", "README.md"]

[dependencies]
cargo_toml = "0.8.1"
clap = "2.3.33"
semver = "0.11.0"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
